name: flutter_instagram_clone
description: Instagram Clone built with flutter and firebase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16
  firebase_storage: ^10.2.16
  uuid: ^3.0.6
  provider: ^6.0.3
  image_picker: ^0.8.5+3
  flutter_svg: ^1.1.0
  cached_network_image: ^3.2.1
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
